api:
  dashboard: true
  insecure: true  # Hanya untuk development

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "traefik-network"
    watch: true

log:
  level: DEBUG

accessLog: {}